dashboard/docopt.py
parse_qc.py

+ used docopt version from `python-extras/2.7.10`

internal docopt import

---

dashboard/templates/base.html
dashboard/templates/getMetricData.html
dashboard/views.py

- Added way to get to MetricData page from any page by going through View dropdown
- Added a button to be able to download data from MetricData as a CSV
- Modified MetricData page to display data in a nice table

Metricdata

---

dashboard/templates/getMetricData.html
dashboard/views.py

CSV file will now be downloaded on client-side. #ndir has been replaced with numdir in the csv.

MetricData Download CSV now on client side. #ndir is numdir on csv

---

dashboard/forms.py
dashboard/models.py
dashboard/templates/add_scan_blacklist_modal.html
dashboard/utils.py
dashboard/views.py
requirements.txt
tests/test_utils.py

Bug fix for issue https://github.com/TIGRLab/admin/issues/1575. This includes changes to dashboard.utils.update_blacklist to allow deletion of an entry, and the addition of a button to the form that pops up from the 'add to blacklist' button.
Also corrected issue with update_blacklist duplicating the first line of a blacklist file when the comment is changed.

Blacklist fix

---

config.py
dashboard/__init__.py
dashboard/task_scheduler.py
dashboard/utils.py
dashboard/views.py
run.py

- Fixed concurrency issues with the scheduled reminder emails
- Improved logging
- Reorganized the config a bit to hopefully make it easier to grok

Scheduled emails bug fixes

---

dashboard/__init__.py
dashboard/models.py
dashboard/templates/scan/header.html
dashboard/templates/scan/header_diffs.html
dashboard/templates/scan/main.html
dashboard/templates/timepoint/sessions/scan_table.html

Adds a warning on the scan table and a table of header diffs on the scan page when header diffs have been found.

Header diffs

---

dashboard/models.py

Needed by datman pull request https://github.com/TIGRLab/datman/pull/204

Added method to share redcap record for linked sessions

---

dashboard/models.py
dashboard/static/css/site.css
dashboard/templates/index.html

Added 'is_open' column to Study table. 
Added CAMH colour labels to CSS.

Modified dashboard main page to display whether study is currently open on the table

---

dashboard/forms.py
dashboard/models.py
dashboard/templates/users/profile.html
dashboard/views.py

A few more small bug fixes (this is the last of them for now! I swear)
1. Redcap records will no longer mistakenly be flagged as different just because their url is/is not unicode
2. The 'new' counter now counts timepoints instead of sessions so the number will match the length of the 'outstanding issues' list
3. Fixed some features that broke when I added the 'site' column to the study_user table
4. Fixed some exceptions that arose when adding / removing study permissions and enabling new user accounts

More bug fixes

---

dashboard/exceptions.py
dashboard/models.py
dashboard/monitors.py
dashboard/redcap.py
dashboard/task_scheduler.py
dashboard/utils.py
dashboard/views.py

1. postgresql database now has new constraint on gold_standards for json_path + contents
2. constraint is implemented in models.py
3. exceptions are pulled out from individual modules into an exceptions.py module

gold standards new constraint and amalgamate exceptions

---

dashboard/emails.py
dashboard/models.py
dashboard/queries.py

- Studies with "email_on_trigger" column will automatically notify users with every incoming scan
- Add queries interface for datman.dashboard to pull all timepoints

Add email notification on new scans 

---

dashboard/queries.py

Quick fix for typo that slid itself into my previous PR for email notifications...

[FIX] - Weird typo in find_sessions

---

dashboard/emails.py

I am a dumbo. '+ \' doesnt allow .format to do its magic when the '{}' are in an earlier part of the string.

[FIX] format and string concatenation issues

---

dashboard/models.py

[FIX] - Fix typo on models.py

---

dashboard/models.py
dashboard/monitors.py

Reverts TIGRLab/dashboard#58 
We discovered circular imports. Oops.

Revert "[FIX] - QC notifications now handled by monitors interface"

---

dashboard/models.py
dashboard/templates/timepoint/main.html
dashboard/templates/timepoint/sessions/main.html
migrations/versions/c5d321b34b54_.py

Depends on https://github.com/TIGRLab/datman/pull/265

[ENH] Add KCNI IDs to the user interface

---

dashboard/datman_utils.py

[FIX] Stop folders from being obliterated when given empty file list

---

dashboard/blueprints/redcap/utils.py
dashboard/models/models.py
migrations/versions/4a842feae63a_.py

This will allow us to configure multiple redcap projects to push to the database with a data entry trigger.

[ENH] Un-hardcode some redcap configuration

---

.github/workflows/check-changes.yml

I was hoping to find a way to keep the github actions config off the master branch, but it seems it has to be merged in. Boo.

[ENH] Add github workflows for changes to master

---

.github/workflows/run-tests.yml
.github/workflows/update-docs.yml

Previous workflows needed updates (werent rebuilding the gh-pages branch)

[FIX] Update github workflows for docs generation
