dashboard/models.py
The papaya viewer was showing the first volume of the file rendered
so for PDT2s this was sometimes a T2 and sometimes a PD file. It will
now always be pointed to the split T2
=> Bug fix: The papaya viewer will now always receive the split T2

dashboard/utils.py, tests/test_utils.py
Fixed at least part of the problem with 'false' being inserted as a database comment when the user clicks the 'delete entry' button repeatedly very quickly.
=> Error on repeated 'delete' clicks

config.py, dashboard/oauth.py, dashboard/views.py
- The fact that the real server is multithreaded meant oauth login was failing sporadically because the 'str_rnd' wasn't persistent. I've temporarily fixed this by moving it into the flask session for the user, but it should probably be in the database later for security reasons. Might also be good to permanently store the user token there.
- The 'GITHUB_PUBLIC' setting was being incorrectly read and always set to True, which made private repo issues unreadable. This is fixed now.
=> Last minute github API related bug fixes

dashboard/models.py, dashboard/monitors.py
Now we can restrict redcap missing emails on a site by site basis!
I've already added all the OPT RA emails to the database, so if this is merged afterwards I just have to add them to the study_user table with the site filled in and restart the server for the changes to take place. Currently it will just be us and the RAs getting them though, do we still need to add PIs to the list at some point?
=> Updated dashboard to allow RA filtering by site

dashboard/models.py
RAs for second sites (e.g. UP2, CU2) were not being recognized because StudyUser was only ever returning one unique study_id/user_id pair.
=> Needed to update StudyUser primary key

dashboard/templates/study_overview_snip.html
Adds emails + first / last names for staff contacts onto the main study page for each study. These studies still need a staff contact set:
NEUR
ASCEND
PASD
CLZ
PASS
VRMD
SPN00
DTI15T
PNSC
PACTMD
SENDEP
=> Add staff contacts and qcers to the 'study info' panel

dashboard/models.py, dashboard/templates/timepoint/sessions/main.html, dashboard/templates/timepoint/sessions/task_files.html
This adds task files to the database and displays a list of task files found for each session on the subject's page of the dashboard.
This query must be run after merging to update the database schema:
```sql
create table session_tasks(
id serial primary key, 
timepoint varchar(64) not null,
repeat integer not null,
task_fname varchar(256) not null,
task_file_path varchar(2048) not null,
foreign key(timepoint, repeat) references sessions(name, num),
unique(task_file_path));
create index on session_tasks(timepoint, repeat);
```
And the corresponded datman pull request should be merged in too.
=> Add basic task file management

dashboard/queries.py
Using the search bar's fuzzy search was causing problems with dm_qc_report, so I added  a very silly function just for exact match with timepoints.
=> Added a wrapper to retrieve timepoints

dashboard/models.py
Need column widths of 3 or more for prelapse session numbers. Making it 48 in case we ever just want to use a whole word or anything
=> Increase column size for bids session

dashboard/models.py, dashboard/templates/study_overview_snip.html
This is to stop the printed list of RAs on the study overview from containing duplicates when a user is an RA to multiple sites
=> Small bug fix

dashboard/models.py, dashboard/monitors.py
- qc notification emails were failing to pass through due to SMTP errors, clients are not configured to send emails - must be done server-side or through the monitors.add_monitor interface.
- models.py now longer directly handles emails and instead interfaces with monitors.py which handles scheduling.
=> [FIX] - QC notifications now handled by monitors interface

dashboard/models.py
This is in response to the recent bug where a redcap record had a typo'd session ID and got mislinked to another session that had previously been marked as not expecting a redcap record. I also made add_redcap check all fields that should never change before allowing updates to be made to the changeable fields (comment/rc_user/event_id).
=> [FIX] Prevent sessions not expecting redcap from having one added

config/__init__.py, config/cluster.py, dashboard/blueprints/redcap/emails.py, dashboard/blueprints/redcap/monitors.py, dashboard/blueprints/redcap/utils.py, dashboard/blueprints/redcap/views.py, dashboard/models/models.py, dashboard/queue.py, dashboard/queue_jobs/data_download.sh, migrations/versions/442e3abe5587_.py
This adds two columns to the study_sites database table that can take the names of a download script and a post download script to submit to the queue. It also adds a monitor function to repeatedly re-submit the download script (for a max of 2 days) until scans have successfully been found and downloaded + launch the post download script on success.
=> [ENH] Add automated session downloading

dashboard/blueprints/redcap/utils.py, dashboard/models/models.py
I accidentally broke the url to view redcap surveys, but this fixes it by re-exposing those config values on the record itself. It also makes the dashboard less spammy when there are multiple instruments configured for a survey that sends DETs.
=> Fix issues with viewing redcap URL

dashboard/blueprints/redcap/utils.py
This is in response to the error messages today. I think a redcap survey was saved without the ID filled in, so the error message left no indications of where to look to fix the error.
=> [FIX] Make it easier to find surveys with bad session IDs / no ID

dashboard/blueprints/redcap/utils.py, dashboard/blueprints/redcap/views.py
It turns out that only a very small subset of survey keys are included in the DET and so when users try to choose a 'completed' field it often is left out and causes uncaught key errors preventing the survey from being pulled in. This fixes that issue and also silences the very spammy and unhelpful debug message in the redcap view
=> [FIX] Stop the 'unparseable request' exceptions for some redcap DETs

config/__init__.py, config/xnat.py, containers/devel/dashboard.env, containers/prod/dashboard.env, dashboard/models/models.py, dashboard/models/utils.py, docs/configuration.rst, migrations/versions/5dc31b2f9fb4_.py, requirements.txt
This adds:
- `dashboard.models.utils` functions to push the data to xnat (in a separate thread to avoid slowness for users)
- New settings added to `dashboard.config` for xnat
- A migration script to update the schema to hold xnat configuration information for each study / site 
- A documentation update for the new config settings.
=> [ENH] Push user QC to XNAT's usability fields

dashboard/models/utils.py
This PR ensures
- That a particular study or site can opt out of pushing QC to xnat by just un-setting the xnat_url in the database https://github.com/TIGRLab/datman-dashboard/commit/ad3b636a1a358c1235190523d89d91ed26ffb9a2
- That a credentials file set for a single site / study can override the environment user/password for xnat  a7e6d238c805433deaa5227e98b31cd2311966ae
- That a more descriptive message will be logged if a study/site hasnt provided a credentials file and the env user/password arent set 490f22a199bd03e39f30d95ec7a93c8af8ab6409
- That comments of 'None' wont be added to XNAT when a user comment isnt given 55d67ebb6fd2d81cef8b3885ca34cf2ea72a6a8a
- That comments that are too long for XNAT will now be truncated to fit 65eeffa16d243e507f8254bd9fd657bd34dc96e6
- That comments …
=> [FIX] Address some edge cases with pushing to XNAT usability fields

bin/parse_config.py, config/database.py, containers/devel/dashboard.env, containers/prod/dashboard.env, dashboard/blueprints/main/views.py, dashboard/blueprints/redcap/utils.py, dashboard/blueprints/users/views.py, dashboard/models/models.py, dashboard/queries.py, docs/configuration.rst, migrations/versions/77bce5fefcf4_.py, tests/conftest.py, tests/test_parse_config.py
First off, let me say sorry that this got so big and disorganized! I had to split this off from another branch that got really out of hand. I'll work harder to keep things small and organized in the future.
This PR adds:
- `bin/parse_config.py` which can be run by a user with permissions to modify the database to read and update all study, site and tag related settings in the database. It also prompts the user for permission to remove records in the database that are no longer defined in the config files (e.g. if a tag was renamed at some point it can purge the old tag and references to it from the database).
- `tests/test_parse_config.py` and `tests/conftest.py` for unit testing parse_config
- An 'expected scans' relationship to track how many of scans with each tag should be found for …
=> [ENH] Add a config parser to update study settings from datman config files

dashboard/queries.py, tests/test_queries.py
This pull request addresses an edge case I found while working on something else. When the AltStudyCode table is empty dashboard.queries.get_studies doesn't return any records when the tag argument is used, even when matching records exist.
- It adds tests that define the correct behavior for dashboard.queries.get_studies f43114565fb21f2a0abb2cd092d1f7db39136c41, 7fc89ff7c3d65c2b412eee9c0036386b0401815c
- Adds a fix for the edge case ff292e2b49ed631c5b491223a16a155607608053
=> [FIX] Add tests to dashboard.queries.get_studies and fix edge case

bin/parse_config.py, dashboard/blueprints/redcap/utils.py, dashboard/models/models.py, migrations/versions/b68a8193acad_.py, tests/test_redcap_bp_utils.py
@josephmje noticed that the event IDs werent being set on redcap records in the database when the dashboard created them. This pull request addresses this issue.
- Add a column on RedcapConfig to store the event name -> event ID mappings 98c0d5179a6896c9789cc968cedfe88555d14278
- Add a migration script to update the database 7a11d629efe86004dfd1974226c3b3b7b1a42649
- Allow parse_config.py to update the event_ids column from the config files 01c97aef1f44ac21de2894a7bc76bd71f24b144c
- Add tests for `dashboard.blueprints.redcap.utils.create_from_request` to describe correct behavior for the function 912556cf6c44ee125df59364ad734670a2411bd6, b6b0641329ac857b573073fa3b06232b06e3e1f3, 8b08ae0a977e78bf4349b9e820d14e3427ec23e8
- Push the event ID for the received event name with the rest of the …
=> [FIX] Start updating redcap record event IDs

.gitignore, config/cluster.py, config/database.py, dashboard/__init__.py, dashboard/blueprints/auth/__init__.py, dashboard/blueprints/handlers/__init__.py, dashboard/blueprints/main/__init__.py, dashboard/blueprints/main/views.py, dashboard/blueprints/redcap/__init__.py, dashboard/blueprints/redcap/utils.py, dashboard/blueprints/redcap/views.py, dashboard/blueprints/scans/__init__.py, dashboard/blueprints/timepoints/__init__.py, dashboard/blueprints/users/__init__.py, dashboard/models/models.py, dashboard/queue.py, dashboard/templates/study.html, docs/index.rst, docs/plugins.rst, migrations/versions/94813db21f13_.py
This pull request 
- Changes how blueprints are registered, so new ones can be added without modifications to `dashboard/__init__.py`
- Adds StudyPipeline and Scope tables to track which QC pipelines are active for each study and how to access QC views
- Modifies the study view html to display links to any QC pipelines configured for the study
- Adds documentation on creating + installing plugins for the dashboard
- Fixes some PEP8 issues
=> [ENH] Allow plugins to be installed

config/misc.py, containers/dashboard.env, dashboard/blueprints/main/utils.py, dashboard/blueprints/main/views.py, dashboard/static/css/qc_dashboard.css, dashboard/templates/study.html, docs/configuration.rst, tests/test_main_bp_utils.py
This pull request will add a display box for studies with a recent nightly run log. The box containers a 'header' line to indicate whether the nightly pipeline is still running or, if finished for the night, a count of the errors reported.
=> [ENH] Add nightly run logs to study home page

config/database.py, docs/configuration.rst
This allows the dashboard to connect to a non-default postgres port. We'll use this to connect to the connection pooler to reduce our connection load issues :)
=> [ENH] Allow a non-standard postgres port to be used

dashboard/blueprints/qc_search/__init__.py, dashboard/blueprints/qc_search/forms.py, dashboard/blueprints/qc_search/static/qc-search.css, dashboard/blueprints/qc_search/static/qc-search.js, dashboard/blueprints/qc_search/templates/qc_search.html, dashboard/blueprints/qc_search/views.py, dashboard/models/models.py, dashboard/queries.py, dashboard/templates/index.html, dashboard/templates/study.html, tests/blueprints/qc_search/test_forms.py, tests/blueprints/qc_search/test_views.py, tests/conftest.py, tests/test_models.py, tests/test_queries.py, tests/utils.py
This PR adds the 'qc_search' blueprint which provides a page for searching through QC records.
Searches are submitted by ajax and results presented like the below image
It also provides a download button for downloading the results as a json file. Links to this new search page are on the main dashboard landing page, and in the header of each study's overview page. 
I've also added tests for much of the newly added code.
@jerdra, @edickie Any comments RE: the user interface changes?
=> [ENH] Add page to search through and download QC records
